version: "3.9"

services:
  backend:
    build:
      context: .
      dockerfile: backend/dockerfile
    volumes:
      - ./backend:/app/backend
    environment:
      - PYTHONUNBUFFERED=1
    ports:
      - "8000:8000"

  # Frontend service to be added on Day 4 