version: "3.9"

services:
  backend:
    build:
      context: .
      dockerfile: backend/dockerfile
    volumes:
      - ./backend:/app/backend
    environment:
      - PYTHONUNBUFFERED=1
      - PYTHONPATH=/app/backend
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_REGION=${AWS_REGION}
      - S3_ENDPOINT_URL=http://localstack:4566
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - OPENAI_MODEL=${OPENAI_MODEL:-gpt-4.1-2025-04-14}
    ports:
      - "8080:8080"
    depends_on:
      - localstack

  frontend:
    image: node:20
    working_dir: /app
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "3001:3001"
    environment:
      - CHOKIDAR_USEPOLLING=true
      - VITE_API_URL=http://backend:8080
    command: sh -c "npm install && npm run dev -- --host 0.0.0.0"
    depends_on:
      - backend

  localstack:
    image: localstack/localstack:3
    environment:
      - SERVICES=s3
      - DEBUG=1
    ports:
      - "4566:4566"
    volumes:
      - localstack_data:/var/lib/localstack

volumes:
  localstack_data: 