FROM python:3.12-slim

WORKDIR /app

COPY backend/pyproject.toml backend/
RUN pip install --upgrade pip && \
    pip install poetry && \
    cd backend && poetry export --without-hashes -f requirements.txt | pip install -r /dev/stdin

COPY backend /app/backend

CMD ["uvicorn", "backend.main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"] 